package com.mycompany.vista;

import com.mycompany.controlador.ControladorBase;
import com.mycompany.controlador.ControladorProveedor;
import com.mycompany.modelo.dao.clases.ClienteDAOImpl;
import com.mycompany.modelo.entidades.Proveedor;
import com.mycompany.vista.ClienteVista;
import com.mycompany.modelo.dao.interfaces.IGenericDAO;
import java.awt.Color;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author alumno
 */
public class ProveedorVista extends javax.swing.JFrame implements IVistaConNIF<Proveedor> {

    private ControladorProveedor controlador;
    private MODO modo = MODO.INACTIVO;

    @Override
    public void limitarEntradaALongitudMinYMax(JTextField campo, int min, int max) {
        campo.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                // Si llegamos a la longitud máxima, bloqueamos
                if (campo.getText().length() >= max) {
                    e.consume();
                }
            }
        });
    }

    @Override
    public void irAPaginaDeInicio() {
        this.dispose();
        new Inicio().setVisible(true);
    }

    @Override
    public void enfocarCampo(String campo) {
        switch (campo) {
            case "campoNIF":
                campoNIF.grabFocus();
                break;
            case "campoNombre":
                campoNombre.grabFocus();
                break;
            case "campoApellidos":
                campoApellidos.grabFocus();
                break;
            case "campoCP":
                campoCP.grabFocus();
                break;
            case "campoTelefono":
                campoTelefono.grabFocus();
                break;
            case "campoMovil":
                campoMovil.grabFocus();
                break;
            case "campoFax":
                campoFax.grabFocus();
                break;
            case "campoEmail":
                campoEmail.grabFocus();
                break;
            case "campoCodigo":
                campoCodigo.grabFocus();
                break;
            default:
                break;
        }
    }

    public enum MODO {
        ALTA,
        BAJA,
        MODIFICACION,
        INACTIVO
    }

    public void setControlador(ControladorProveedor controlador) {
        this.controlador = controlador;
    }

    /**
     * Creates new form Proyecto
     */
    public ProveedorVista(ControladorProveedor controlador) {
        this.controlador = controlador;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campoCodigo = new javax.swing.JTextField();
        campoNIF = new javax.swing.JTextField();
        letraNif = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        campoApellidos = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        campoDomicilio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        campoCP = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        campoLocalidad = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        campoTelefono = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        campoMovil = new javax.swing.JTextField();
        campoTotalCompras = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        campoEmail = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        campoFax = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        botonAceptar = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        Mantenimiento = new javax.swing.JMenu();
        menuAlta = new javax.swing.JMenuItem();
        menuBaja = new javax.swing.JMenuItem();
        menuModificacion = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        Volver = new javax.swing.JMenuItem();
        menuConsultas = new javax.swing.JMenu();
        informaCodigo = new javax.swing.JMenuItem();
        menuListados = new javax.swing.JMenu();
        listadoPorCodigo = new javax.swing.JMenuItem();
        listadoEntreCodigos = new javax.swing.JMenuItem();
        listadoGrafico = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Código");

        jLabel2.setText("NIF");

        jLabel3.setText("Nombre");

        jLabel4.setText("Apellidos");

        jLabel5.setText("Domicilio");

        jLabel6.setText("Teléfono");

        jLabel7.setText("Localidad");

        jLabel8.setText("Código Postal");

        jLabel9.setText("Movil");

        jLabel10.setText("Fax");

        jLabel11.setText("e-mail");

        jLabel12.setText("Total compras");

        botonAceptar.setText("Aceptar");
        botonAceptar.setEnabled(false);

        botonSalir.setText("Salir");
        botonSalir.setEnabled(false);

        botonCancelar.setText("Cancelar");
        botonCancelar.setEnabled(false);

        Mantenimiento.setText("Mantenimiento");

        menuAlta.setText("Alta");
        Mantenimiento.add(menuAlta);

        menuBaja.setText("Baja");
        Mantenimiento.add(menuBaja);

        menuModificacion.setText("Modificacion");
        Mantenimiento.add(menuModificacion);
        Mantenimiento.add(jSeparator1);

        Volver.setText("Volver");
        Mantenimiento.add(Volver);

        jMenuBar1.add(Mantenimiento);

        menuConsultas.setText("Consultas");

        informaCodigo.setText("Por Codigo");
        menuConsultas.add(informaCodigo);

        menuListados.setText("Listados");

        listadoPorCodigo.setText("Por Codigo");
        menuListados.add(listadoPorCodigo);

        listadoEntreCodigos.setText("Entre Codigos");
        menuListados.add(listadoEntreCodigos);

        listadoGrafico.setText("Grafico");
        menuListados.add(listadoGrafico);

        menuConsultas.add(menuListados);

        jMenuBar1.add(menuConsultas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5)
                    .addComponent(campoDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(campoApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(campoNIF, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(letraNif, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(campoCP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(campoTelefono, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(campoLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(campoMovil, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(campoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10)
                                .addComponent(campoFax, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(campoTotalCompras))))
                .addContainerGap(59, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoNIF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letraNif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoMovil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoFax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoTotalCompras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAceptar)
                    .addComponent(botonSalir)
                    .addComponent(botonCancelar))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        IGenericDAO clienteDAO = new ClienteDAOImpl();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Mantenimiento;
    private javax.swing.JMenuItem Volver;
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonSalir;
    private javax.swing.JTextField campoApellidos;
    private javax.swing.JTextField campoCP;
    private javax.swing.JTextField campoCodigo;
    private javax.swing.JTextField campoDomicilio;
    private javax.swing.JTextField campoEmail;
    private javax.swing.JTextField campoFax;
    private javax.swing.JTextField campoLocalidad;
    private javax.swing.JTextField campoMovil;
    private javax.swing.JTextField campoNIF;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JTextField campoTelefono;
    private javax.swing.JTextField campoTotalCompras;
    private javax.swing.JMenuItem informaCodigo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextField letraNif;
    private javax.swing.JMenuItem listadoEntreCodigos;
    private javax.swing.JMenuItem listadoGrafico;
    private javax.swing.JMenuItem listadoPorCodigo;
    private javax.swing.JMenuItem menuAlta;
    private javax.swing.JMenuItem menuBaja;
    private javax.swing.JMenu menuConsultas;
    private javax.swing.JMenu menuListados;
    private javax.swing.JMenuItem menuModificacion;
    // End of variables declaration//GEN-END:variables

    @Override
    public void limpiarCampos() {
        campoApellidos.setText("");
        campoNombre.setText("");
        letraNif.setText("");
        campoNIF.setText("");
        campoCodigo.setText("");
        campoDomicilio.setText("");
        campoLocalidad.setText("");
        campoCP.setText("");
        campoTelefono.setText("");
        campoMovil.setText("");
        campoFax.setText("");
        campoTotalCompras.setText("");
        campoEmail.setText("");
    }

    @Override
    public void estadoCampos(boolean estado) {
        campoApellidos.setEnabled(estado);
        campoNombre.setEnabled(estado);
        campoDomicilio.setEnabled(estado);
        campoLocalidad.setEnabled(estado);
        campoCP.setEnabled(estado);
        campoTelefono.setEnabled(estado);
        campoMovil.setEnabled(estado);
        campoFax.setEnabled(estado);

        botonAceptar.setEnabled(estado);
        botonCancelar.setEnabled(estado);
        botonSalir.setEnabled(estado);
        campoEmail.setEnabled(estado);
        campoNIF.setEnabled(estado);

        if (modo == MODO.INACTIVO) {
            campoCodigo.setEnabled(estado);
        } else {
            campoCodigo.setEnabled(!estado);
        }

        if (!estado) {
            campoCodigo.grabFocus();
        } else {
            campoNIF.grabFocus();
        }

        if (modo == MODO.ALTA && estado) {
            campoTotalCompras.setText("0");
        }
    }

    @Override
    public void mostrarMensaje(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje);
    }

    @Override
    public Proveedor obtenerEntidadDelFormulario() {
        Proveedor p = new Proveedor();
        try {
            p.setCodigo(Integer.parseInt(campoCodigo.getText()));
        } catch (NumberFormatException e) {
            p.setCodigo(-1);
        }

        p.setNif(campoNIF.getText() + letraNif.getText());
        p.setNombre(campoNombre.getText());
        p.setApellidos(campoApellidos.getText());
        p.setDomicilio(campoDomicilio.getText());
        p.setLocalidad(campoLocalidad.getText());
        p.setCodigoPostal(campoCP.getText());
        p.setTelefono(campoTelefono.getText());
        p.setMovil(campoMovil.getText());
        p.setFax(campoFax.getText());
        p.setEmail(campoEmail.getText());

        try {
            p.setTotalCompras(Float.parseFloat(campoTotalCompras.getText()));
        } catch (NumberFormatException e) {
            p.setTotalCompras(0);
        }
        return p;
    }

    @Override
    public void mostrarEntidad(Proveedor entidad) {
        if (entidad == null) {
            return;
        }
        campoCodigo.setText(String.valueOf(entidad.getCodigo()));

        String nifCompleto = entidad.getNif();
        campoNIF.setText(nifCompleto.substring(0, 8));
        letraNif.setText(nifCompleto.substring(8));
        campoNombre.setText(entidad.getNombre());
        campoApellidos.setText(entidad.getApellidos());
        campoDomicilio.setText(entidad.getDomicilio());
        campoLocalidad.setText(entidad.getLocalidad());
        campoCP.setText(entidad.getCodigoPostal());
        campoTelefono.setText(entidad.getTelefono());
        campoMovil.setText(entidad.getMovil());
        campoFax.setText(entidad.getFax());
        campoEmail.setText(entidad.getEmail());
        campoTotalCompras.setText(String.valueOf(entidad.getTotalCompras()));
    }

    @Override
    public int obtenerCodigoEntidad() {
        try {
            return Integer.parseInt(campoCodigo.getText());
        } catch (NumberFormatException e) {
            return -1;
        }
    }

    @Override
    public void estadoInicial() {
        modo = MODO.INACTIVO;
        cancelarAccion();
        campoTotalCompras.setEnabled(false);
        letraNif.setEnabled(false);
    }

    @Override
    public void cancelarAccion() {
        limpiarCampos();
        estadoCampos(false);
    }

    @Override
    public void limitarEntradaLetrasConLongitudMinYMax(JTextField campo, int min, int max) {
        campo.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                if (!Character.isLetter(e.getKeyChar())) {
                    e.consume();
                    return;
                }
                if (campo.getText().length() >= max) {
                    e.consume();
                }
            }
        });
    }

    @Override
    public void limitarEntradaACifraConLongitudExacta(JTextField campo, int longitud) {
        campo.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                if (!Character.isDigit(e.getKeyChar())) {
                    e.consume();
                    return;
                }
                if (campo.getText().length() >= longitud) {
                    e.consume();
                }
            }
        });
    }

    @Override
    public void comprobarEmail(JTextField campo) {
        campo.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent e) {
                String texto = campo.getText().trim();
                String patron = "^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$";
                if (!texto.matches(patron)) {
                    campo.setBackground(Color.PINK);
                } else {
                    campo.setBackground(Color.WHITE);
                }
            }
        });
    }

    @Override
    public int obtenerCifrasNIF() {
        int cifras = 0;
        try {
            cifras = Integer.parseInt(campoNIF.getText());
        } catch (NumberFormatException e) {
            e.printStackTrace();
        }
        return cifras;
    }

    @Override
    public void establecerLetraNIF(String letra) {
        letraNif.setText(letra);
    }
}
