
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.Iterator;
import javax.swing.AbstractButton;
import javax.swing.ButtonModel;
import java.awt.event.KeyEvent;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author alumno
 */
public class Proyecto extends javax.swing.JFrame {

    /**
     * Creates new form Proyecto
     */
    public Proyecto() {
        initComponents();
        formularioNuevo(false);


    }

    // Operacion 1
    // -----------------------------------------
    // Método para gestionar el formulario nuevo
    // -----------------------------------------
    private void formularioNuevo(boolean estado) {
        // -------------------------------
        // Gestión de la seleccion inicial
        // -------------------------------
        seleccionProductos(procesador2, memoria4, monitor4, discoduro4);
        seleccionCheckBox(true, false, false, false);
        // ----------------------------
        // Desactivar grupos de botones
        // ----------------------------
        gestionarGrupos(false);

        // -----------------------------
        // Desactivar resto de elementos
        // -----------------------------
        botonesClientes(estado, estado, estado);
        gestionarCheckBox(estado);
        desactivarElemento(comboLocalidad, estado);

    }

    // -----------------------
    // Gestionar estado grupos
    // -----------------------
    public void gestionarGrupos(boolean estado) {
        desactivarElemento(grupoDiscoDuro, estado);
        desactivarElemento(grupoMemoria, estado);
        desactivarElemento(grupoMonitor, estado);
        desactivarElemento(grupoProcesador, estado);
    }

    // ---------------------------------
    // Gestionar estado botones clientes
    // ---------------------------------
    public void botonesClientes(boolean anadir, boolean buscar, boolean eliminar) {
        botonAñadir.setEnabled(anadir);
        botonBuscar.setEnabled(buscar);
        botonEliminar.setEnabled(eliminar);
    }

    // ---------------------------
    // Gestionar estado checkboxes
    // ---------------------------
    public void gestionarCheckBox(boolean estado) {
        desactivarElemento(opcion2, estado);
        desactivarElemento(opcion1, estado);
        desactivarElemento(opcion4, estado);
        desactivarElemento(opcion3, estado);
    }

    // --------------------
    // Desactivar elementos
    // --------------------
    private void desactivarElemento(javax.swing.JComponent elemento, boolean estado) {
        elemento.setEnabled(estado);
    }

    // --------------------
    // Desactivar elementos
    // --------------------
    private void desactivarElemento(javax.swing.ButtonGroup bg, boolean estadoBotones) {
        Enumeration<AbstractButton> botones = bg.getElements(); //Crea un enum con los botones del grupo

        Iterator<AbstractButton> iteradorBotones = botones.asIterator();//Crea un iterador con los botones del enum
        while (iteradorBotones.hasNext()) {
            desactivarElemento(iteradorBotones.next(), estadoBotones);
        }

    }

    // ------------------------------------
    // Método para establecer una selección
    // ------------------------------------
    public void seleccionProductos(
            javax.swing.JRadioButton procesador,
            javax.swing.JRadioButton memoria,
            javax.swing.JRadioButton monitor,
            javax.swing.JRadioButton discoduro
    ) {
        procesador.setSelected(true);
        memoria.setSelected(true);
        monitor.setSelected(true);
        discoduro.setSelected(true);

    }

    // --------------------
    // Selección checkboxes
    // --------------------
    public void seleccionCheckBox(boolean estado1, boolean estado2, boolean estado3, boolean estado4) {
        opcion1.setSelected(estado1);
        opcion2.setSelected(estado2);
        opcion3.setSelected(estado3);
        opcion4.setSelected(estado4);

    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoProcesador = new javax.swing.ButtonGroup();
        grupoMemoria = new javax.swing.ButtonGroup();
        grupoMonitor = new javax.swing.ButtonGroup();
        grupoDiscoDuro = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        comboLocalidad = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaClientes = new javax.swing.JList<>();
        botonCancelar = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        botonAñadir = new javax.swing.JButton();
        botonBuscar = new javax.swing.JButton();
        botonEliminar = new javax.swing.JButton();
        opcion2 = new javax.swing.JCheckBox();
        opcion1 = new javax.swing.JCheckBox();
        opcion4 = new javax.swing.JCheckBox();
        opcion3 = new javax.swing.JCheckBox();
        discoduro1 = new javax.swing.JRadioButton();
        discoduro2 = new javax.swing.JRadioButton();
        discoduro3 = new javax.swing.JRadioButton();
        discoduro4 = new javax.swing.JRadioButton();
        monitor1 = new javax.swing.JRadioButton();
        monitor2 = new javax.swing.JRadioButton();
        monitor3 = new javax.swing.JRadioButton();
        monitor4 = new javax.swing.JRadioButton();
        memoria4 = new javax.swing.JRadioButton();
        memoria1 = new javax.swing.JRadioButton();
        memoria2 = new javax.swing.JRadioButton();
        memoria3 = new javax.swing.JRadioButton();
        procesador2 = new javax.swing.JRadioButton();
        procesador1 = new javax.swing.JRadioButton();
        procesador4 = new javax.swing.JRadioButton();
        procesador3 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 0));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre del cliente");

        campoNombre.setActionCommand("<Not Set>");
        campoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNombreActionPerformed(evt);
            }
        });
        campoNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoNombreKeyPressed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Localidad");

        comboLocalidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Villalba", "Galapagar", "Las Rozas", "Majadahonda" }));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Lista de clientes");

        listaClientes.setToolTipText("");
        jScrollPane1.setViewportView(listaClientes);

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        botonSalir.setText("Salir");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Procesador");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Memoria");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Monitor");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Disco Duro");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Opciones");

        botonAñadir.setText("Añadir");
        botonAñadir.setToolTipText("");

        botonBuscar.setText("Buscar");

        botonEliminar.setText("Eliminar");

        opcion2.setText("Wifi");
        opcion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcion2ActionPerformed(evt);
            }
        });

        opcion1.setSelected(true);
        opcion1.setText("Grabador DVD");

        opcion4.setText("Backup/Restore");
        opcion4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcion4ActionPerformed(evt);
            }
        });

        opcion3.setText("Sintonizador TV");
        opcion3.setToolTipText("");
        opcion3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcion3ActionPerformed(evt);
            }
        });

        grupoDiscoDuro.add(discoduro1);
        discoduro1.setText("60  Gb");

        grupoDiscoDuro.add(discoduro2);
        discoduro2.setText("80  Gb");

        grupoDiscoDuro.add(discoduro3);
        discoduro3.setText("120 Gb");

        grupoDiscoDuro.add(discoduro4);
        discoduro4.setSelected(true);
        discoduro4.setText("200 Gb");

        grupoMonitor.add(monitor1);
        monitor1.setText("15''");

        grupoMonitor.add(monitor2);
        monitor2.setText("17''");

        grupoMonitor.add(monitor3);
        monitor3.setText("TFT 15''");

        grupoMonitor.add(monitor4);
        monitor4.setSelected(true);
        monitor4.setText("TFT 17''");

        grupoMemoria.add(memoria4);
        memoria4.setSelected(true);
        memoria4.setText("1024 Mb");

        grupoMemoria.add(memoria1);
        memoria1.setText("128   Mb");

        grupoMemoria.add(memoria2);
        memoria2.setText("256   Mb");

        grupoMemoria.add(memoria3);
        memoria3.setText("512   Mb");

        grupoProcesador.add(procesador2);
        procesador2.setSelected(true);
        procesador2.setText("P4 3.2 Gb");

        grupoProcesador.add(procesador1);
        procesador1.setText("P4 3.0 Gb");

        grupoProcesador.add(procesador4);
        procesador4.setText("AMD 650");

        grupoProcesador.add(procesador3);
        procesador3.setText("P4 Celeron");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addComponent(procesador4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(procesador1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(procesador2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(procesador3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(memoria1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(memoria2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(memoria3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(memoria4, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(monitor1)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(monitor2)
                                    .addComponent(monitor3)
                                    .addComponent(monitor4))
                                .addGap(90, 90, 90)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(discoduro2)
                                    .addComponent(discoduro1)
                                    .addComponent(discoduro3)
                                    .addComponent(discoduro4)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(59, 59, 59)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(opcion1)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(opcion2)
                                    .addComponent(opcion4)
                                    .addComponent(opcion3))
                                .addGap(28, 28, 28))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(26, 26, 26)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(botonAñadir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(comboLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jLabel7)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(opcion1)
                            .addComponent(discoduro1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(opcion2)
                            .addComponent(discoduro2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(opcion3)
                            .addComponent(discoduro3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(opcion4)
                            .addComponent(discoduro4)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(monitor1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(monitor2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(monitor3)
                        .addGap(4, 4, 4)
                        .addComponent(monitor4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(memoria1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(memoria2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(memoria3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(memoria4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(procesador1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(procesador2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(procesador3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(procesador4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(botonAñadir)
                        .addComponent(botonBuscar)
                        .addComponent(botonEliminar))
                    .addComponent(botonCancelar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonSalir)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opcion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcion2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcion2ActionPerformed

    private void opcion4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcion4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcion4ActionPerformed

    private void opcion3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcion3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcion3ActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void campoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNombreActionPerformed

    private void campoNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoNombreKeyPressed
    // Operacion 2
    // -------------------------------------------------------------------
    // Método que activa el formulario al realizar una acción en el Nombre
    // -------------------------------------------------------------------
        String nombre = campoNombre.getText();
        if (evt.getKeyCode() == KeyEvent.VK_ENTER && !nombre.isEmpty() && nombre.length() <= 15) {
            // ----------------------------
            // Desactivar grupos de botones
            // ----------------------------
            gestionarGrupos(true);

            // -----------------------------
            // Desactivar resto de elementos
            // -----------------------------
            botonesClientes(true, true, false);
            gestionarCheckBox(true);
            desactivarElemento(comboLocalidad, true);
            
            //Foco sobre localidad
            comboLocalidad.grabFocus();

        }
    
    }//GEN-LAST:event_campoNombreKeyPressed
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Proyecto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAñadir;
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonSalir;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JComboBox<String> comboLocalidad;
    private javax.swing.JRadioButton discoduro1;
    private javax.swing.JRadioButton discoduro2;
    private javax.swing.JRadioButton discoduro3;
    private javax.swing.JRadioButton discoduro4;
    private javax.swing.ButtonGroup grupoDiscoDuro;
    private javax.swing.ButtonGroup grupoMemoria;
    private javax.swing.ButtonGroup grupoMonitor;
    private javax.swing.ButtonGroup grupoProcesador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listaClientes;
    private javax.swing.JRadioButton memoria1;
    private javax.swing.JRadioButton memoria2;
    private javax.swing.JRadioButton memoria3;
    private javax.swing.JRadioButton memoria4;
    private javax.swing.JRadioButton monitor1;
    private javax.swing.JRadioButton monitor2;
    private javax.swing.JRadioButton monitor3;
    private javax.swing.JRadioButton monitor4;
    private javax.swing.JCheckBox opcion1;
    private javax.swing.JCheckBox opcion2;
    private javax.swing.JCheckBox opcion3;
    private javax.swing.JCheckBox opcion4;
    private javax.swing.JRadioButton procesador1;
    private javax.swing.JRadioButton procesador2;
    private javax.swing.JRadioButton procesador3;
    private javax.swing.JRadioButton procesador4;
    // End of variables declaration//GEN-END:variables
}
